# Site settings
title: Jessica Trowbridge
email: jesstro@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  PhD Student in Public Health
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jesstro.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
